name: Build WordPress ZIP

on:
  release:
    types: [published, edited]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer PHP et Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, curl, json

      # 3️⃣ Installer les dépendances Composer
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 4️⃣ Préparer le dossier du plugin
      - name: Prepare plugin folder
        run: |
          PLUGIN_NAME=acf-icons
          BUILD_DIR=${PLUGIN_NAME}-build

          mkdir -p $BUILD_DIR

          # Copier les fichiers nécessaires
          rsync -av --exclude='.git*' --exclude='*.zip' --exclude='vendor' ./ $BUILD_DIR/

          # Copier le dossier vendor généré par Composer
          cp -r vendor $BUILD_DIR/vendor

      # 5️⃣ Créer le ZIP final
      - name: Create ZIP file
        run: |
          PLUGIN_NAME=acf-icons
          zip -r ${PLUGIN_NAME}-${{ github.ref_name }}.zip ${PLUGIN_NAME}-build

      # 6️⃣ Attacher le ZIP à la release
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: acf-icons-${{ github.ref_name }}.zip