name: Build ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer PHP et Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, curl, json
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist

      # 3️⃣ Créer un dossier temporaire pour le ZIP
      - name: Prepare plugin folder
        run: |
          mkdir acf-icons-build
          cp -r acf-icons/* acf-icons-build/
          cp -r vendor acf-icons-build/vendor

      # 4️⃣ Créer le ZIP
      - name: Create ZIP file
        run: |
          zip -r acf-icons-${{ github.ref_name }}.zip acf-icons-build
        shell: bash

      # 5️⃣ Publier le ZIP comme asset de release
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: acf-icons-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
